import type { BomNode, Operation, BomCompositionItem } from './types';

export const initialBomCompositionList: BomCompositionItem[] = [
  {
    id: 'mat-comp-1',
    sortIdx: 1,
    itemSeq: 1,
    materialCode: 'IF20251125007',
    materialName: 'NAND Flash芯片',
    bomVersion: '-',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '采购, 自制',
    specification: '256GB',
    brand: '-',
    inventory: 0,
    unit: '个 (Pcs)',
    standardUsage: 1.0000,
    totalDemand: 10,
    scrapRate: 0,
    remark: ''
  },
  {
    id: 'mat-comp-2',
    sortIdx: 2,
    itemSeq: 2,
    materialCode: 'ITEM_TYPE_0135-004',
    materialName: '邱test5',
    bomVersion: '-',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '采购, 自制',
    specification: '1',
    brand: '-',
    inventory: 0,
    unit: '公顷',
    standardUsage: 1.0000,
    totalDemand: 10,
    scrapRate: 0,
    remark: ''
  },
  {
    id: 'mat-comp-3',
    sortIdx: 3,
    itemSeq: 3,
    materialCode: 'PRT-2026-0092',
    materialName: '不锈钢钣金外壳',
    bomVersion: 'V1.0',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '自制',
    specification: 'SUS304 2mm',
    brand: '-',
    inventory: 450,
    unit: '套',
    standardUsage: 1.0000,
    totalDemand: 10,
    scrapRate: 0.5,
    remark: '注意打磨毛刺'
  },
  {
    id: 'mat-comp-4',
    sortIdx: 4,
    itemSeq: 4,
    materialCode: 'EL-SW-1102',
    materialName: '微动开关',
    bomVersion: '-',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '采购',
    specification: '5V 0.1A',
    brand: 'OMRON',
    inventory: 12000,
    unit: '个',
    standardUsage: 4.0000,
    totalDemand: 40,
    scrapRate: 1.0,
    remark: ''
  },
  {
    id: 'mat-comp-5',
    sortIdx: 5,
    itemSeq: 5,
    materialCode: 'FST-SCR-M4',
    materialName: 'M4十字盘头螺丝',
    bomVersion: '-',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '采购',
    specification: 'M4*12',
    brand: '-',
    inventory: 35000,
    unit: '颗',
    standardUsage: 16.0000,
    totalDemand: 160,
    scrapRate: 2.0,
    remark: '不锈钢镀黑锌'
  },
  {
    id: 'mat-comp-6',
    sortIdx: 6,
    itemSeq: 6,
    materialCode: 'PCB-MAIN-26',
    materialName: '主控电路板 (PCBA)',
    bomVersion: 'V2.1',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '委外',
    specification: '6层沉金',
    brand: '-',
    inventory: 12,
    unit: '片',
    standardUsage: 1.0000,
    totalDemand: 10,
    scrapRate: 0,
    remark: '需静电包装'
  },
  {
    id: 'mat-comp-7',
    sortIdx: 7,
    itemSeq: 7,
    materialCode: 'CBL-PWR-001',
    materialName: '电源线束',
    bomVersion: '-',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '采购',
    specification: 'AWG18 500mm',
    brand: 'Molex',
    inventory: 150,
    unit: '条',
    standardUsage: 1.0000,
    totalDemand: 10,
    scrapRate: 0,
    remark: ''
  },
  {
    id: 'mat-comp-8',
    sortIdx: 8,
    itemSeq: 8,
    materialCode: 'PKG-BOX-22',
    materialName: '工业瓦楞纸箱',
    bomVersion: '-',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '采购',
    specification: '500*400*300mm',
    brand: '-',
    inventory: 40,
    unit: '个',
    standardUsage: 1.0000,
    totalDemand: 10,
    scrapRate: 0,
    remark: '含缓冲珍珠棉'
  },
  {
    id: 'mat-comp-9',
    sortIdx: 9,
    itemSeq: 9,
    materialCode: 'LBL-SN-001',
    materialName: '防伪SN标签',
    bomVersion: '-',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '采购',
    specification: '40*20mm',
    brand: '-',
    inventory: 5000,
    unit: '张',
    standardUsage: 1.0000,
    totalDemand: 10,
    scrapRate: 1,
    remark: '打印流水号'
  },
  {
    id: 'mat-comp-13',
    sortIdx: 13,
    itemSeq: 13,
    materialCode: 'STL-M3-10',
    materialName: '不锈钢螺丝 M3x10',
    bomVersion: '-',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '自制',
    specification: 'M3*10',
    brand: '-',
    inventory: 500,
    unit: '颗',
    standardUsage: 10.0000,
    totalDemand: 100,
    scrapRate: 0,
    remark: ''
  },
  {
    id: 'mat-comp-14',
    sortIdx: 14,
    itemSeq: 14,
    materialCode: 'PLT-500-2',
    materialName: '铝合金侧板 2mm',
    bomVersion: 'V1.0',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '自制',
    specification: '2mm',
    brand: '-',
    inventory: 100,
    unit: '件',
    standardUsage: 2.0000,
    totalDemand: 20,
    scrapRate: 1,
    remark: ''
  },
  {
    id: 'mat-comp-10',
    sortIdx: 10,
    itemSeq: 10,
    materialCode: 'MOT-STP-42',
    materialName: '42步进电机',
    bomVersion: 'V1.0',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '采购',
    specification: '42BYGH47-401A',
    brand: 'NEMA',
    inventory: 80,
    unit: '台',
    standardUsage: 2.0000,
    totalDemand: 20,
    scrapRate: 0,
    remark: ''
  },
  {
    id: 'mat-comp-11',
    sortIdx: 11,
    itemSeq: 11,
    materialCode: 'BLT-TNG-2M',
    materialName: 'PU同步带',
    bomVersion: '-',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '采购',
    specification: '2GT-6mm',
    brand: '-',
    inventory: 350,
    unit: '米',
    standardUsage: 0.5000,
    totalDemand: 5,
    scrapRate: 5,
    remark: '按需裁切'
  },
  {
    id: 'mat-comp-12',
    sortIdx: 12,
    itemSeq: 12,
    materialCode: 'SNS-OPT-02',
    materialName: '光电传感器',
    bomVersion: '-',
    imageUrl: '',
    category: '钣金件',
    businessAttr: '采购',
    specification: 'NPN常开',
    brand: 'SICK',
    inventory: 15,
    unit: '个',
    standardUsage: 4.0000,
    totalDemand: 40,
    scrapRate: 0,
    remark: ''
  }
];

const productOperations: Operation[] = [
  { id: 'op-p-1', stepIdx: 1, opCode: 'OP-PGM', opName: '编程下图', workCenter: '技术规划站', equipmentCode: 'EQ-DWG-01', equipmentName: 'CAD/CAM工作站', isEnabled: true, executionType: 'SELF', reportingType: 'TIME' },
  { id: 'op-p-2', stepIdx: 2, opCode: 'OP-CNC', opName: 'CNC加工', workCenter: 'CNC数控中心', equipmentCode: 'EQ-CNC-01', equipmentName: '精雕加工中心', isEnabled: true, executionType: 'SELF', reportingType: 'PIECE' },
  { id: 'op-p-3', stepIdx: 3, opCode: 'OP-LATHE', opName: '车床加工', workCenter: '车工车间', equipmentCode: 'EQ-LTH-01', equipmentName: '数控车床', isEnabled: true, executionType: 'SELF', reportingType: 'PIECE' },
  { id: 'op-p-4', stepIdx: 4, opCode: 'OP-MILL', opName: '机加铣床', workCenter: '铣床车间', equipmentCode: 'EQ-MIL-01', equipmentName: '立式铣床', isEnabled: true, executionType: 'SELF', reportingType: 'PIECE' },
  { id: 'op-p-5', stepIdx: 5, opCode: 'OP-WIRE', opName: '慢走丝特种线割', workCenter: '【外协】昆山信捷特种加工中心', equipmentCode: '-', equipmentName: '-', isEnabled: true, executionType: 'OUTSOURCE', reportingType: 'PIECE', supplierName: '昆山信捷特种线割加工中心' },
  { id: 'op-p-6', stepIdx: 6, opCode: 'OP-TAP', opName: '攻牙', workCenter: '攻丝组装区', equipmentCode: 'EQ-TAP-01', equipmentName: '多轴攻牙机', isEnabled: true, executionType: 'SELF', reportingType: 'PIECE' },
];

const subAssemblyOperations: Operation[] = [
  { id: 'op-s-1', stepIdx: 1, opCode: 'OP-CUT', opName: '下料', workCenter: '钣金加工中心', equipmentCode: 'EQ-SHT-01', equipmentName: '数控冲床', isEnabled: true, executionType: 'SELF' },
  { id: 'op-s-2', stepIdx: 2, opCode: 'OP-WELD', opName: '焊接', workCenter: '焊接车间', equipmentCode: 'EQ-WLD-01', equipmentName: '激光焊接机器人', isEnabled: true, executionType: 'SELF' },
  { id: 'op-s-3', stepIdx: 3, opCode: 'OP-PAINT', opName: '表面粉末喷涂', workCenter: '【外协】东莞创联特种喷涂实业厂', equipmentCode: '-', equipmentName: '-', isEnabled: true, executionType: 'OUTSOURCE', reportingType: 'PIECE', supplierName: '东莞市创联特种喷涂实业厂' },
];

const materialOperations: Operation[] = [
  { id: 'op-m-1', stepIdx: 1, opCode: 'OP-INSP', opName: '来料检验 (IQC)', workCenter: '品管部', equipmentCode: 'EQ-IQC-01', equipmentName: '三坐标测量机', isEnabled: true, executionType: 'SELF' },
  { id: 'op-m-2', stepIdx: 2, opCode: 'OP-BAKE', opName: '烘烤预处理', workCenter: '烘烤房', equipmentCode: 'EQ-BAK-01', equipmentName: '高温老化房', isEnabled: true, executionType: 'SELF' },
];

const sheetMetalStandardOperations = (prefix: string): Operation[] => [
  { id: `${prefix}-1`, stepIdx: 1, opCode: 'OP-DRAW', opName: '展图', workCenterCode: 'WS-01', workCenter: '技术展图站', equipmentCode: 'EQ-DWG-01', equipmentName: 'CAD绘图工作站', isEnabled: true, executionType: 'SELF', reportingType: 'TIME' },
  { id: `${prefix}-2`, stepIdx: 2, opCode: 'OP-LASER', opName: '激光下料', workCenterCode: 'WS-02', workCenter: '激光切割站', equipmentCode: 'EQ-LSR-01', equipmentName: '大族激光切割机', isEnabled: true, executionType: 'SELF', reportingType: 'PIECE' },
  { id: `${prefix}-3`, stepIdx: 3, opCode: 'OP-NEST', opName: '排版', workCenterCode: 'WS-03', workCenter: '套裁排版站', equipmentCode: 'EQ-NST-01', equipmentName: '排版服务器', isEnabled: true, executionType: 'SELF', reportingType: 'TIME' },
  { id: `${prefix}-4`, stepIdx: 4, opCode: 'OP-BEND', opName: '折弯', workCenterCode: 'WS-04', workCenter: '数控折弯站', equipmentCode: 'EQ-BND-01', equipmentName: '亚威数控折弯机', isEnabled: true, executionType: 'SELF', reportingType: 'PIECE' },
  { id: `${prefix}-5`, stepIdx: 5, opCode: 'OP-WELD', opName: '焊接', workCenterCode: 'WS-05', workCenter: '焊接车间', equipmentCode: 'EQ-WLD-01', equipmentName: '激光焊接机器人', isEnabled: true, executionType: 'SELF', reportingType: 'PIECE' },
  { id: `${prefix}-6`, stepIdx: 6, opCode: 'OP-FITTER', opName: '钳工', workCenterCode: 'WS-06', workCenter: '钳工工作站', equipmentCode: 'EQ-FIT-01', equipmentName: '多功能钳工台', isEnabled: true, executionType: 'SELF', reportingType: 'PIECE' },
  { id: `${prefix}-7`, stepIdx: 7, opCode: 'OP-POLISH', opName: '打磨', workCenterCode: 'WS-07', workCenter: '打磨抛光站', equipmentCode: 'EQ-POL-01', equipmentName: '无尘打磨机', isEnabled: true, executionType: 'SELF', reportingType: 'PIECE' },
  { id: `${prefix}-8`, stepIdx: 8, opCode: 'OP-OXIDE', opName: '表面阳极氧化', workCenterCode: 'WS-OUTSOURCE', workCenter: '【外协】宏发表面热处理有限公司', equipmentCode: '-', equipmentName: '-', isEnabled: true, executionType: 'OUTSOURCE', reportingType: 'PIECE', supplierName: '深圳市宏发表面热处理有限公司' }
];

export const initialBomTree: BomNode = {
  id: 'node-root',
  type: 'PRODUCT',
  code: 'A-00004',
  name: '送板机 (Loader)',
  operations: productOperations,
  children: [
    {
      id: 'node-mat-1',
      type: 'MATERIAL',
      code: 'IF20251125007',
      name: 'NAND Flash芯片',
      operations: materialOperations,
    },
    {
      id: 'node-sub-1',
      type: 'SUBASSEMBLY',
      code: 'ITEM_TYPE_0135-004',
      name: '机械结构类机箱',
      operations: subAssemblyOperations,
      children: [
        {
          id: 'node-mat-2',
          type: 'MATERIAL',
          code: 'STL-M3-10',
          name: '不锈钢螺丝 M3x10',
          operations: sheetMetalStandardOperations('op-screw'),
        },
        {
          id: 'node-mat-3',
          type: 'MATERIAL',
          code: 'PLT-500-2',
          name: '铝合金侧板 2mm',
          operations: sheetMetalStandardOperations('op-plate'),
        },
      ]
    }
  ]
};

export const initialTasks: import('./types').ProductionTask[] = [
  {
    id: 'task-1',
    taskCode: 'PT-2026-001',
    operationName: 'SMT贴片',
    materialName: '智能手机主板组装',
    employee: '张三',
    position: 'SMT操作员',
    workStationCode: 'WS-SMT-01',
    workStationName: 'SMT贴片线A段',
    requiredQuantity: 100,
    completedQuantity: 45,
    plannedStartTime: '2026-06-10 08:00',
    plannedEndTime: '2026-06-11 18:00',
    estimatedEndTime: '2026-06-11 17:30',
    remark: '优先处理加急订单',
    status: '生产中',
    reportType: '计件'
  },
  {
    id: 'task-2',
    taskCode: 'PT-2026-002',
    operationName: '光纤融接',
    materialName: '光模块部件',
    employee: '李四',
    position: '装配工',
    workStationCode: 'WS-ASM-03',
    workStationName: '无尘装配室3号',
    requiredQuantity: 200,
    completedQuantity: 0,
    plannedStartTime: '2026-06-12 09:00',
    plannedEndTime: '2026-06-13 12:00',
    estimatedEndTime: '2026-06-13 12:00',
    remark: '需要防静电作业',
    status: '待生产',
    reportType: '计件'
  },
  {
    id: 'task-3',
    taskCode: 'PT-2026-003',
    operationName: '系统老化测试',
    materialName: '智能手机',
    employee: '王五',
    position: '测试工程师',
    workStationCode: 'WS-TEST-01',
    workStationName: '高低温老化箱',
    requiredQuantity: 50,
    completedQuantity: 50,
    plannedStartTime: '2026-06-08 08:00',
    plannedEndTime: '2026-06-09 20:00',
    estimatedEndTime: '2026-06-09 19:00',
    remark: '24小时连续运行',
    status: '已完成',
    reportType: '计时'
  }
];

export const mockSalesOrders: import('./types').SalesOrder[] = [
  {
    orderNo: 'SO-20260601-001',
    customer: '华为技术有限公司',
    orderDate: '2026-06-01',
    planDeliveryDate: '2026-06-30',
    startDate: '2026-06-10',
    endDate: '2026-06-28',
    status: '已生效',
    products: [
      {
        id: 'so-prod-101',
        lineNo: 1,
        productCode: 'PROD001',
        productName: '智能手机A型 (Pro Max)',
        category: '智能终端',
        specification: '6.5寸全面屏 8G+256G 黑色',
        routingName: '智能手机组装标准路线',
        bomVersion: 'V2.1',
        unit: '台',
        orderQuantity: 500,
        productionQuantity: 500,
        customer: '华为技术有限公司',
        planDeliveryDate: '2026-06-30',
        startDate: '2026-06-10',
        endDate: '2026-06-28',
        remark: '优先保证屏幕贴合良率'
      },
      {
        id: 'so-prod-102',
        lineNo: 2,
        productCode: 'A-00004',
        productName: '自动送板机 (Loader)',
        category: '自动化装备',
        specification: '标准SMT上板机 宽轨双向进出',
        routingName: '送板机精密制造路线',
        bomVersion: 'V1.0',
        unit: '台',
        orderQuantity: 50,
        productionQuantity: 50,
        customer: '华为技术有限公司',
        planDeliveryDate: '2026-06-30',
        startDate: '2026-06-10',
        endDate: '2026-06-25',
        remark: '需配备加厚导轨'
      },
      {
        id: 'so-prod-103',
        lineNo: 3,
        productCode: 'GW-5G-08',
        productName: '5G工业智能网关',
        category: '通信设备',
        specification: '工业级全网通 4口LAN/WAN 导轨安装',
        routingName: '工业网关精密焊接装配线',
        bomVersion: 'V1.5',
        unit: '台',
        orderQuantity: 200,
        productionQuantity: 200,
        customer: '华为技术有限公司',
        planDeliveryDate: '2026-06-30',
        startDate: '2026-06-12',
        endDate: '2026-06-27',
        remark: '外壳需通过高低温老化'
      }
    ]
  },
  {
    orderNo: 'SO-20260605-002',
    customer: '小米通信技术有限公司',
    orderDate: '2026-06-05',
    planDeliveryDate: '2026-07-15',
    startDate: '2026-06-15',
    endDate: '2026-07-10',
    status: '已生效',
    products: [
      {
        id: 'so-prod-201',
        lineNo: 1,
        productCode: 'ROB-V3-PRO',
        productName: '智能扫地机器人 V3',
        category: '智能家电',
        specification: 'LDS激光导航 5000Pa双盘旋擦',
        routingName: '扫地机器人精益装配线',
        bomVersion: 'V3.0',
        unit: '台',
        orderQuantity: 300,
        productionQuantity: 300,
        customer: '小米通信技术有限公司',
        planDeliveryDate: '2026-07-15',
        startDate: '2026-06-15',
        endDate: '2026-07-10',
        remark: '配双边刷配件包'
      },
      {
        id: 'so-prod-202',
        lineNo: 2,
        productCode: 'LCK-FACE-01',
        productName: '智能人脸识别门锁 Pro',
        category: '智能安防',
        specification: '3D结构光人脸+半导体指纹+防撬报警',
        routingName: '智能门锁电子机械装配路线',
        bomVersion: 'V1.2',
        unit: '套',
        orderQuantity: 450,
        productionQuantity: 450,
        customer: '小米通信技术有限公司',
        planDeliveryDate: '2026-07-15',
        startDate: '2026-06-16',
        endDate: '2026-07-12',
        remark: '锁体不锈钢防锯'
      },
      {
        id: 'so-prod-203',
        lineNo: 3,
        productCode: 'PROD001',
        productName: '智能手机A型 (Pro Max)',
        category: '智能终端',
        specification: '6.5寸全面屏 8G+256G 黑色',
        routingName: '智能手机组装标准路线',
        bomVersion: 'V2.1',
        unit: '台',
        orderQuantity: 250,
        productionQuantity: 250,
        customer: '小米通信技术有限公司',
        planDeliveryDate: '2026-07-15',
        startDate: '2026-06-15',
        endDate: '2026-07-10',
        remark: '定制品牌挂绳'
      }
    ]
  },
  {
    orderNo: 'SO-20260610-003',
    customer: '比亚迪精密制造有限公司',
    orderDate: '2026-06-10',
    planDeliveryDate: '2026-08-01',
    startDate: '2026-06-20',
    endDate: '2026-07-25',
    status: '已生效',
    products: [
      {
        id: 'so-prod-301',
        lineNo: 1,
        productCode: 'AUTO-DSP-15',
        productName: '车载中控旋转大屏 15.6寸',
        category: '汽车电子',
        specification: '车规级2K OLED窄边框 8核8G',
        routingName: '车载显示模组百级无尘装配线',
        bomVersion: 'V2.0',
        unit: '套',
        orderQuantity: 180,
        productionQuantity: 180,
        customer: '比亚迪精密制造有限公司',
        planDeliveryDate: '2026-08-01',
        startDate: '2026-06-20',
        endDate: '2026-07-25',
        remark: '满足TS16949车规出厂检验'
      },
      {
        id: 'so-prod-302',
        lineNo: 2,
        productCode: 'CHG-WLS-50',
        productName: '50W车载无线快充模块',
        category: '汽车电子',
        specification: '主动风冷散热 双线圈Qi标准',
        routingName: '车载充电模组PCBA制造线',
        bomVersion: 'V1.0',
        unit: '个',
        orderQuantity: 800,
        productionQuantity: 800,
        customer: '比亚迪精密制造有限公司',
        planDeliveryDate: '2026-08-01',
        startDate: '2026-06-22',
        endDate: '2026-07-26',
        remark: '需配防滑耐高温硅胶垫'
      }
    ]
  },
  {
    orderNo: 'SO-20260612-004',
    customer: '联想集团有限公司',
    orderDate: '2026-06-12',
    planDeliveryDate: '2026-07-20',
    startDate: '2026-06-18',
    endDate: '2026-07-18',
    status: '已生效',
    products: [
      {
        id: 'so-prod-401',
        lineNo: 1,
        productCode: 'PROD001',
        productName: '智能手机A型 (Pro Max)',
        category: '智能终端',
        specification: '6.5寸全面屏 8G+256G 黑色',
        routingName: '智能手机组装标准路线',
        bomVersion: 'V2.1',
        unit: '台',
        orderQuantity: 300,
        productionQuantity: 300,
        customer: '联想集团有限公司',
        planDeliveryDate: '2026-07-20',
        startDate: '2026-06-18',
        endDate: '2026-07-18',
        remark: '定制企业版固件'
      },
      {
        id: 'so-prod-402',
        lineNo: 2,
        productCode: 'A-00004',
        productName: '自动送板机 (Loader)',
        category: '自动化装备',
        specification: '标准SMT上板机 宽轨双向进出',
        routingName: '送板机精密制造路线',
        bomVersion: 'V1.0',
        unit: '台',
        orderQuantity: 20,
        productionQuantity: 20,
        customer: '联想集团有限公司',
        planDeliveryDate: '2026-07-20',
        startDate: '2026-06-18',
        endDate: '2026-07-15',
        remark: '增配安全急停保护光幕'
      },
      {
        id: 'so-prod-403',
        lineNo: 3,
        productCode: 'GW-5G-08',
        productName: '5G工业智能网关',
        category: '通信设备',
        specification: '工业级全网通 4口LAN/WAN 导轨安装',
        routingName: '工业网关精密焊接装配线',
        bomVersion: 'V1.5',
        unit: '台',
        orderQuantity: 150,
        productionQuantity: 150,
        customer: '联想集团有限公司',
        planDeliveryDate: '2026-07-20',
        startDate: '2026-06-20',
        endDate: '2026-07-16',
        remark: '附带工业防雷模块'
      }
    ]
  }
];

export const defaultStockProducts: import('./types').SalesOrderProduct[] = [
  {
    id: 'stock-prod-1',
    lineNo: 1,
    productCode: 'PROD001',
    productName: '智能手机A型 (Pro Max)',
    category: '智能终端',
    specification: '6.5寸全面屏 8G+256G 黑色',
    routingName: '智能手机组装标准路线',
    bomVersion: 'V2.1',
    unit: '台',
    orderQuantity: 200,
    productionQuantity: 200,
    customer: '内部库存中心',
    planDeliveryDate: '2026-06-30',
    startDate: '2026-06-10',
    endDate: '2026-06-25',
    remark: '常规备货'
  },
  {
    id: 'stock-prod-2',
    lineNo: 2,
    productCode: 'A-00004',
    productName: '自动送板机 (Loader)',
    category: '自动化装备',
    specification: '标准SMT上板机 宽轨双向进出',
    routingName: '送板机精密制造路线',
    bomVersion: 'V1.0',
    unit: '台',
    orderQuantity: 30,
    productionQuantity: 30,
    customer: '内部库存中心',
    planDeliveryDate: '2026-06-30',
    startDate: '2026-06-10',
    endDate: '2026-06-25',
    remark: '安全库存补充'
  },
  {
    id: 'stock-prod-3',
    lineNo: 3,
    productCode: 'GW-5G-08',
    productName: '5G工业智能网关',
    category: '通信设备',
    specification: '工业级全网通 4口LAN/WAN 导轨安装',
    routingName: '工业网关精密焊接装配线',
    bomVersion: 'V1.5',
    unit: '台',
    orderQuantity: 100,
    productionQuantity: 100,
    customer: '内部库存中心',
    planDeliveryDate: '2026-06-30',
    startDate: '2026-06-10',
    endDate: '2026-06-25',
    remark: '战略备货'
  }
];
